### ISSUE TITLE
Errors on executing tests

### ISSUE THREAD

**Issue by Daeinar** [dedis/drand#1]
When executing the tests, I am currently receiving the following errors:

### Error 1

```
goroutine 86 [running]:
gopkg.in/dedis/kyber.v1/share/pedersen/vss.(*aggregator).DealCertified(0x0, 0xc420100500)
        /Users/cosh/Code/go/src/gopkg.in/dedis/kyber.v1/share/pedersen/vss/vss.go:597 +0x37
gopkg.in/dedis/kyber.v1/share/pedersen/dkg.(*DistKeyGenerator).qualIter(0xc420381180, 0xc420213958)
        /Users/cosh/Code/go/src/gopkg.in/dedis/kyber.v1/share/pedersen/dkg/dkg.go:282 +0xb3
gopkg.in/dedis/kyber.v1/share/pedersen/dkg.(*DistKeyGenerator).QUAL(0xc420381180, 0xc4202139c0, 0xc4202139c8, 0xc420020000)
        /Users/cosh/Code/go/src/gopkg.in/dedis/kyber.v1/share/pedersen/dkg/dkg.go:261 +0x66
gopkg.in/dedis/kyber.v1/share/pedersen/dkg.(*DistKeyGenerator).Certified(0xc420381180, 0x43d24a8)
        /Users/cosh/Code/go/src/gopkg.in/dedis/kyber.v1/share/pedersen/dkg/dkg.go:251 +0x2b
github.com/dedis/drand.(*DKG).checkCertified(0xc42010ed80)
        /Users/cosh/Code/go/src/github.com/dedis/drand/dkg.go:163 +0x8d
panic(0x435b000, 0x459d620)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
gopkg.in/dedis/kyber.v1/share/pedersen/vss.(*aggregator).verifyResponse(0x0, 0xc42014a880, 0x4014582, 0xc42034e118)
        /Users/cosh/Code/go/src/gopkg.in/dedis/kyber.v1/share/pedersen/vss/vss.go:533 +0x4a
gopkg.in/dedis/kyber.v1/share/pedersen/vss.(*Verifier).ProcessResponse(0xc420122080, 0xc42014a880, 0x4, 0xc420380208)
        /Users/cosh/Code/go/src/gopkg.in/dedis/kyber.v1/share/pedersen/vss/vss.go:410 +0x39
gopkg.in/dedis/kyber.v1/share/pedersen/dkg.(*DistKeyGenerator).ProcessResponse(0xc420381180, 0xc420530260, 0x4, 0xc4201de198, 0x1)
        /Users/cosh/Code/go/src/gopkg.in/dedis/kyber.v1/share/pedersen/dkg/dkg.go:211 +0x7b
github.com/dedis/drand.(*DKG).processTmpResponses(0xc42010ed80, 0xc420142260)
        /Users/cosh/Code/go/src/github.com/dedis/drand/dkg.go:125 +0x29f
github.com/dedis/drand.(*DKG).processDeal(0xc42010ed80, 0xc42013d9a0, 0xc420142260)
        /Users/cosh/Code/go/src/github.com/dedis/drand/dkg.go:97 +0x2d6
github.com/dedis/drand.(*DKG).process(0xc42010ed80, 0xc42013d9a0, 0xc42048c2a0)
        /Users/cosh/Code/go/src/github.com/dedis/drand/dkg.go:80 +0x86
github.com/dedis/drand.(*Drand).processMessages(0xc420154960)
        /Users/cosh/Code/go/src/github.com/dedis/drand/drand.go:169 +0x368
created by github.com/dedis/drand.NewDrand
        /Users/cosh/Code/go/src/github.com/dedis/drand/drand.go:70 +0x1fb
exit status 2
```

### Error 2

```
goroutine 28 [running]:
github.com/dedis/drand.(*Router).handleConnection(0xc42005e9c0, 0xc4200e86e0, 0x4573e40, 0xc42000e0c0)
        /Users/cosh/Code/go/src/github.com/dedis/drand/network.go:364 +0x188
created by github.com/dedis/drand.(*Router).connect
        /Users/cosh/Code/go/src/github.com/dedis/drand/network.go:309 +0x157
exit status 2
```

**Comment by nikkolasg** [comment]
Both should be resolved by now.

**Comment by Daeinar** [comment]
Great, works now! Closing.
