### ISSUE TITLE
port number missing gives a panic

### ISSUE THREAD

**Issue by jeffallen** [dedis/drand#45]
With this public file:

```
Address = "dedis.nella.org"
Key = "0181683b428f3c6a67cddff09117f87a52b4797dbafd05eb0b0876d3bbd79874f978152ca614c17a2537a80baa794c98c3ba95e535d874bef88643a71676bc612c31c64aff0363f56cb44bb8650e69bc96c0976c6edab918e38e018f6c6e42a38c7400244e5e9e2aff0fa7d22b46526852a4a02885d233f3ed8ed8c3ec85b4c286"
TLS = true
```

I got this panic:

```
panic: listen tcp: address dedis.nella.org: missing port in address

goroutine 1 [running]:
github.com/dedis/drand/net.NewGrpcGatewayFromCertManager(0xc420423720, 0xf, 0x7ffc1d9f521c, 0x37, 0x7ffc1d9f525e, 0x35, 0xc42000c088, 0xa52980, 0xc420170120, 0x0, ...) 
        /Users/jallen/go/src/github.com/dedis/drand/net/gateway.go:59 +0x16e
github.com/dedis/drand/core.initDrand(0xa54ac0, 0xc420156120, 0xc42009c000, 0xc4200225a0, 0xc4201999d0, 0xc4201beb70)
        /Users/jallen/go/src/github.com/dedis/drand/core/drand.go:86 +0x263
github.com/dedis/drand/core.LoadDrand(0xa54ac0, 0xc420156120, 0xc42009c000, 0xc420156120, 0x0, 0x0)
        /Users/jallen/go/src/github.com/dedis/drand/core/drand.go:94 +0x43
main.runCmd(0xc42001f080, 0xc42016ec78, 0x892891)
        /Users/jallen/go/src/github.com/dedis/drand/main.go:336 +0x274
main.main.func5(0xc42001f080, 0x100, 0xc42001f080)
        /Users/jallen/go/src/github.com/dedis/drand/main.go:151 +0x30
github.com/dedis/drand/vendor/github.com/urfave/cli.HandleAction(0x90ad60, 0xa0a0d8, 0xc42001f080, 0xc42001c400, 0x0)
        /Users/jallen/go/src/github.com/dedis/drand/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/dedis/drand/vendor/github.com/urfave/cli.Command.Run(0x9e20aa, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa00144, 0x3e, 0x0, ...)
        /Users/jallen/go/src/github.com/dedis/drand/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/dedis/drand/vendor/github.com/urfave/cli.(*App).Run(0xc42008f040, 0xc42001c0c0, 0x6, 0x6, 0x0, 0x0)
        /Users/jallen/go/src/github.com/dedis/drand/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
        /Users/jallen/go/src/github.com/dedis/drand/main.go:187 +0x1aef
```

**Comment by PizzaWhisperer** [comment]
PR #53 closes this issue
